Repository ansible-collections/vmware.vmware_rest, pull requests merged in 2024-08, with the labels that each got.

#506 Mention vmware.vmware.vcsa_settings
  changelogs/fragments/506-mention_vmware.vmware.vcsa_settings.yml
  config/modules.yaml
Labels: mergeit

#510 Mm feature/fix broken doc generation
  .github/workflows/docs-pr.yml
  .github/workflows/docs-push.yml
  changelogs/fragments/510-fix-broken-doc-generation.yml
  config/modules.yaml
  docs/docsite/rst/dev_guide.rst
  docs/docsite/rst/index.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter_vm_customize/index.rst
  plugins/modules/content_locallibrary.py
  plugins/modules/content_subscribedlibrary.py
  plugins/modules/vcenter_storage_policies_info.py
  plugins/modules/vcenter_vm.py
  plugins/modules/vcenter_vm_hardware_disk.py
  plugins/modules/vcenter_vm_power.py
  plugins/modules/vcenter_vm_storage_policy.py
Labels: mergeit

#495 Remove support for ansible-core 2.14
  .github/workflows/sanity-tests.yaml
  README.md
  changelogs/fragments/492-remove-support-ansible-2-14.yml
  meta/runtime.yml
  tests/sanity/ignore-2.14.txt
Labels: mergeit

#513 Add vmware.vmware for docs CI
  .github/workflows/docs-pr.yml
  changelogs/fragments/513-add-vmware.vmware-for-docs-ci.yaml
Labels: mergeit

#514 README: Add Communication section with Forum information
  README.md
Labels: mergeit

#516 README: Add forum group
  README.md
Labels: mergeit

#520 release 3.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/503_mm-feature_update_lookup_docs.yml
  changelogs/fragments/506-mention_vmware.vmware.vcsa_settings.yml
  changelogs/fragments/510-fix-broken-doc-generation.yml
  changelogs/fragments/513-add-vmware.vmware-for-docs-ci.yaml
  galaxy.yml
Labels: skip-changelog

#521 Drop Publish Collection Docs workflow
  .github/workflows/docs-push.yml
Labels: mergeit

#524 Drop scenario guide
  changelogs/fragments/524-drop-scenaros.yml
  docs/docsite/extra-docs.yml
  docs/docsite/rst/guide_vmware_rest.rst
  docs/docsite/rst/vmware_rest_scenarios/appliance/appliance_access.rst
  docs/docsite/rst/vmware_rest_scenarios/appliance/health.rst
  docs/docsite/rst/vmware_rest_scenarios/appliance/network.rst
  docs/docsite/rst/vmware_rest_scenarios/appliance/services.rst
  docs/docsite/rst/vmware_rest_scenarios/appliance/system_managment.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/1_authentication.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/1_installation.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/2_collect_information.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/3_create_vm.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/4_vm_info.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/5_vm_hardware_tuning.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/6_run_a_vm.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/7_vm_tool_information.rst
  docs/docsite/rst/vmware_rest_scenarios/vcenter/8_vm_tool_configuration.rst
Labels: documentation, docs, mergeit

#525 release 4.0.1
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/524-drop-scenaros.yml
  galaxy.yml
Labels: mergeit

#522 update readme to match certified content template
  README.md
  changelogs/fragments/522-update-readme-format.yaml
Labels: mergeit
